# Generated by Django 4.2.1 on 2023-05-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Link',
            new_name='ProjectLink',
        ),
        migrations.RenameModel(
            old_name='Skill_Link',
            new_name='SkillLink',
        ),
    ]
