# Generated by Django 4.2.1 on 2023-05-14 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_aboutlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlink',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutlinks', to='portfolio.about'),
        ),
    ]
