# Generated by Django 4.2.1 on 2023-05-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_aboutlink_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlink',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_links', to='portfolio.about'),
        ),
        migrations.AlterField(
            model_name='aboutlink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts_l', to='portfolio.link'),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_l', to='portfolio.link'),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_links', to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='skilllink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_l', to='portfolio.link'),
        ),
        migrations.AlterField(
            model_name='skilllink',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_links', to='portfolio.skill'),
        ),
    ]
