# Generated by Django 4.2.1 on 2023-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_projectlink_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('LP', 'Linguagens de Programação'), ('F', 'Ferramentas'), ('D', 'Dados'), ('AW', 'Aplicação Web')], max_length=128),
        ),
    ]
