# Generated by Django 4.2.1 on 2023-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('LP', 'Linguagens de Programação'), ('F', 'Ferramentas'), ('BD', 'Banco de Dados'), ('D', 'Bibliotecas para dados'), ('W', 'Aplicação Web')], max_length=128),
        ),
    ]
