# Generated by Django 4.2.1 on 2023-05-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('KAGGLE', 'Kaggle'), ('CERTIFICATE', 'Certificado'), ('INSTAGRAM', 'Instagram'), ('EMAIL', 'E-mail'), ('OTHER', 'Outros')], max_length=128),
        ),
    ]
